exp_name: ffn_concat_32_128_32_simpleEncoder_cifar
#train_filenames: '/home/ishit/textures_dataset/dtd/train_filenames.txt'
#val_filenames: '/home/ishit/textures_dataset/dtd/val_filenames.txt'
#root_dir: '/home/ishit/textures_dataset/dtd/images/'
train_filenames: '/home/ishit/cifar/train_filenames.txt'
val_filenames: '/home/ishit/cifar/val_filenames.txt'
root_dir: '/home/ishit/cifar'

model:
    hyper: False
    local: True # True, False
    layers: 4
    width: 256
    embedding: ffn # pe, ffn, False
    N_freqs: 256
    synthesis_activation: relu # relu, sine
    modulation_activation: False # relu, false
    encoder: True # True, False

training:
    epochs: 10000
    lr: 0.0001
    batch_size: 128

image:
    size: 32
    channels: 3
    crop_size: 32
    
latent:
    dim: 128
    var_factor: 0.001

loss:
    reg_lam: 0.001

logging:
    image_step: 1000
    scalars_step: 100
    image_vis_count: 10

log_dir: logs
gpu: 0
