#exp_name: modsiren_32_256_32_skip_simpleEncoder_cifar_largeconv
exp_name: ae
#train_filenames: '/home/ishit/localImages/img_generalization/img_align_celeba/filenames.txt'
#val_filenames: '/home/ishit/localImages/img_generalization/img_align_celeba/val_filenames.txt'
#root_dir: '/home/ishit/localImages/img_generalization/img_align_celeba/'
#train_filenames: '/home/ishit/textures_dataset/dtd/train_filenames.txt'
#val_filenames: '/home/ishit/textures_dataset/dtd/val_filenames.txt'
#root_dir: '/home/ishit/textures_dataset/dtd/images/'
train_filenames: '/home/ishit/cifar/train_filenames.txt'
val_filenames: '/home/ishit/cifar/val_filenames.txt'
root_dir: '/home/ishit/cifar'

model:
    hyper: False
    local: True # True, False
    layers: 4
    width: 256
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: sine # relu, sine
    modulation_activation: relu # relu, false
    encoder: True # True, False
    encoder_type: 'simple' # Large, simple

training:
    epochs: 10000
    lr: 0.0001
    batch_size: 128

image:
    size: 32
    channels: 3
    crop_size: 32
    
latent:
    dim: 256
    var_factor: 0.001

loss:
    reg_lam: 0.001

logging:
    image_step: 1000
    scalars_step: 100
    image_vis_count: 10

log_dir: temp_logs
gpu: 0
