exp_name: modsiren_64_512_64_skip
train_filenames: '/home/ishit/textures_dataset/dtd/train_filenames.txt'
val_filenames: '/home/ishit/textures_dataset/dtd/val_filenames.txt'
root_dir: '/home/ishit/textures_dataset/dtd/images/'

model:
    hyper: False
    local: True # True, False
    layers: 4
    width: 512
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: sine # relu, sine
    modulation_activation: relu # relu, false
    encoder: True # True, False

training:
    epochs: 10000
    lr: 0.0001
    batch_size: 8

image:
    size: 64
    channels: 3
    crop_size: 64
    
latent:
    dim: 512
    var_factor: 0.001

loss:
    reg_lam: 0.001

logging:
    image_step: 100
    scalars_step: 100

log_dir: logs
gpu: 0
