exp_name: modsiren_32_256_superres_diff
train_filenames: '/home/ishit/localImages/img_generalization/img_align_celeba/filenames.txt'
val_filenames: '/home/ishit/localImages/img_generalization/img_align_celeba/val_filenames.txt'
root_dir: '/home/ishit/localImages/img_generalization/img_align_celeba/'

model:
    hyper: False
    local: True # True, False
    layers: 4
    width: 256
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: sine # relu, sine
    modulation_activation: relu # relu, false
    encoder: True # True, False
    encoder_type: 'simple' # Large, simple
    decoder: False

training:
    epochs: 200
    lr: 0.0001
    batch_size: 16

image:
    size: 128
    channels: 3
    crop_size: 128
    train_size: 60000
    val_size: 10000
    
latent:
    dim: 256
    var_factor: 0.001

loss:
    reg_lam: 0.001

logging:
    image_step: 1000
    scalars_step: 100
    image_vis_count: 10

log_dir: /newfoundland2/ishit/logs_superres
gpu: 0
