exp_name: ffn
im_path: data/castle2.jpg

model:
    local: False # True, False
    layers: 4
    width: 256
    embedding: pe # pe, ffn, False
    N_freqs: 10
    synthesis_activation: relu # relu, sine
    modulation_activation: False # relu, false
    encoder: False

training:
    epochs: 5000
    lr: 0.0001
    batch_size: 64

image:
    size: 256
    cells: 8
    channels: 3 
    
latent:
    dim: 64
    var_factor: 0.001

loss:
    reg_lam: 0.001

logging:
    image_step: 1000
    scalars_step: 100

log_dir: logs
gpu: 0
