hparams = {
        "latent_dim": 128,
        "cells": 8,
        "net_width": 128,
        "num_images": 1000,
        "filter_radius": 0,
        "n_layers": 3,
        "imsize": 256,
        "train_datapath": "img_align_celeba_sampled/train",
        "val_datapath": "img_align_celeba/val",
        "exp_name": "parabola",
        "epochs": 5000,
        "batch_size": 8,
        "lr": 5e-5,
        "val_lr": 1e-2,
        "val_optim_steps": 1,
        "val_frequency": 10000,
        "l2_weight": 1,
        "d_weight": 0,
        "lpips_weight": 0,
        "reg_weight": 0,
        "reg_lam": 0,
        "shuffle": True
        }
