exp_name: localrelu
root_dir: /newfoundland2/ishit/threedscas_points/

model:
    hyper: False
    local: True # True, False
    layers: 5 
    width: 256
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: relu # relu, sine
    modulation_activation: false # relu, false
    freq_scale: 1.
    concat: True
    encoder: False

training:
    epochs: 100000
    model_lr: 0.0001
    latent_lr: 0.0001
    batch_size: 16
    sample_size: 1024
    total_points: 1000000
    mode: 'train'

shape:
    n_voxels: 32
    clamp: 1
    n_shapes: 100
    
latent:
    dim: 128
    var_factor: 0.01

loss:
    reg_lam: 0.0

logging:
    shape_log: 20000

eval_points: 100000
log_dir: /newfoundland2/ishit/logs_multi_shape_2
gpu: 0
