exp_name: ffn
#points_path: data/dragon_2_points_2.npy
#sdf_path: data/dragon_2_sdf_2.npy
#mesh_path: data/dragon_2_gt.ply
points_path: /home/ishit/Documents/shape_datasets/all_shapes_processed_global/Lion_points.npy
sdf_path: /home/ishit/Documents/shape_datasets/all_shapes_processed_global/Lion_sdf.npy
mesh_path: /home/ishit/Documents/shape_datasets/all_shapes_processed_global/Lion.ply
model:
    hyper: False
    local: False # True, False
    layers: 4
    width: 256
    embedding: ffn # pe, ffn, False
    N_freqs: 256
    synthesis_activation: relu # relu, sine
    modulation_activation: false # relu, false
    freq_scale: 2.
    concat: True

training:
    epochs: 100
    model_lr: 0.0001
    latent_lr: 0.0000
    batch_size: 1
    sample_size: 16384
    total_points: 2500000
    mode: 'train'

shape:
    n_voxels: 1
    clamp: 1
    
latent:
    dim: 128
    var_factor: 0.0

loss:
    reg_lam: 0.0

eval_points: 100000
#log_dir: /newfoundland2/ishit/dragon_logs
log_dir: data_logs
gpu: 0
