exp_name: local_relu
im_path: data/castle2.jpg

model:
    hyper: False
    local: True # True, False
    layers: 4
    width: 256
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: relu # relu, sine
    modulation_activation: false # relu, false
    freq_scale: 1.
    concat: False
    encoder: True # True, False
    encoder_type: 'simple' # Large, simple
    decoder: False

training:
    epochs: 500
    lr: 0.0001
    batch_size: 64
    mode: 'train'

image:
    size: 2048
    tile_size: 32
    cells: 64
    channels: 3
    
latent:
    dim: 64
    var_factor: 0.001

loss:
    reg_lam: 0.1

logging:
    image_step: 1000
    scalars_step: 500

log_dir: data_logs/
gpu: 0
