exp_name: localrelu_woe_1024
vid_path: data/bikes.npy

model:
    local: True # True, False
    layers: 4
    width: 512
    embedding: False # pe, ffn, False
    N_freqs: 256
    synthesis_activation: relu # relu, sine
    modulation_activation: False # relu, false
    encoder: False

training:
    epochs: 1000
    lr: 0.0001
    batch_size: 8

video:
    cells: [25, 8, 20]
    channels: 3
    
latent:
    dim: 1024    
    var_factor: 1

loss:
    reg_lam: 0.001

logging:
    image_step: 1000 
    scalars_step: 100

log_dir: logs
gpu: 0

